---
- name: 0) 인벤토리 변수 테스트 복구
  hosts: all
  tasks:
    - name: 1) 패키지 삭제
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent

      loop:
        - httpd
        - mariadb-server
        - php
        - mutt
