---
- name: Play 01) 고급 웹서버 복구
  hosts: ansible1.example.com
  vars_files:
    - vars/vars.yml
  tasks:
    # 1) 방화벽 포트 제거
    - name: 1) 방화벽 포트 제거
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled

      loop:
        - http
        - https

    # 2. 웹 서비스 중지
    - name: 2) 웹 서비스 중지
      ansible.builtin.systemd:
        name: "{{ web_svc }}"
        state: stopped
        enabled: false

    # 3) 설정 파일 삭제 - index.html
    - name: 3) 설정 파일 삭제 - index.html
      ansible.builtin.file:
        path: "{{ web_root }}/index.html"
        state: absent

    # 3) 설정 파일 삭제 - secret module 삭제
    - name: 3) 설정 파일 삭제 - secret
      ansible.builtin.file:
        path: "{{ secrets_dest }}"
        state: absent

    # 3) 설정 폴더 삭제 - secret 삭제
    - name: 3) 설정 폴더 삭제  - secrets_dir
      ansible.builtin.file:
        path: "{{ secrets_dir }}"
        state: absent

    - name: 3) 설정 파일 삭제 - /.htaccess
      ansible.builtin.file:
        path: "{{ web_root }}/.htaccess"
        state: absent

    # 4) 패키지 제거
    - name: 4) 패키지 삭제
      ansible.builtin.dnf:
        name:
          - "{{ web_pkg }}"
          - "{{ ssl_pkg }}"
        state: absent
