---
- name: 0) 웹 서비스 설치 및 서비스
  hosts: webserver
  tasks:
    - name: 1) 패키지 설치
      ansible.builtin.yum:
        name: "{{ ansible_local.custom.general.package }}"
        state: present

    - name: 2) 서비스 시작
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - httpd
        - firewalld

    - name: 3) 방화벽 시작
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
