---
- name: 0) 웹 서비스 설치 및 서비스
  hosts: webserver
  tasks:
    - name: 1) 패키지 설치
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ ansible_local.custom.general.package }}"
        - firewalld
    - name: 2) 서비스 시작
      ansible.builtin.systemd:
        service: "{{ item }}"
        state: "{{ ansible_local.custom.general.state }}"
      loop:
        - "{{ ansible_local.custom.general.service }}"
        - firewalld

    - name: 3) 방화벽 등록
      ansible.posix.firewalld:
        service: "{{ ansible_local.custom.general.fwsvc }}"
        permanent: true
        immediate: true
        state: enabled
