---
- name: 원격 펙트 구성
  hosts: webserver
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: 원격 폴더 생성
      ansible.builtin.file:
        state: directory
        recurse: true
        path: "{{ remote_dir }}"

    - name: 펙트 설치 진행
      ansible.builtin.copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
        mode: '0644'
