---
# tasks file for myfirewall
#############################################
# 1) 방화벽 패키지 설치
# 2) 방화벽 서비스 시작
#############################################
- name: 1) 방화벽 패키지 설치
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: 2) 방화벽 서비스 시작
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: 3) 방화벽 포트 등록
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ web_rules }}"
