---
- name: 0) 시간 동기화 작업
  hosts: datacenters
  gather_facts: true
  vars_files:
    - group_var/asia_datacenter/timezone.yml
  tasks:
    - name: 1) NTP 서버 시간 동기화
      ansible.builtin.import_role:
        name: rhel-system-roles.timesync

    - name: 2) TimeZone 설정
      # Asia/Seoul TimeZone
      community.general.timezone:
        name: "{{ host_timezone }}"
      notify: Restart_chrony
  handlers:
    - name: Restart_chrony
      ansible.builtin.systemd:
        service: chronyd
        state: restarted
