---
- name: 0) 시간 서버 복구
  hosts: all
  gather_facts: false
  tasks:
    - name: 1) TimeZone 설정
      community.general.timezone:
        name: Asia/Seoul

    - name: 2) NTP 서버 시간 동기화
      ansible.builtin.import_role:
        name: rhel-system-roles.timesync
      vars:
        timesync_ntp_servers:
          - hostname: kr.pool.ntp.org
            ibrust: true
