---
- name: 0) 웹 서버 설정
  hosts: webservers
  tasks:
    ##########################################
    # Play01:
    # 1) 웹 서버 패키지 설치 및 서비스 기동 - include_tasks
    # 2) 방화벽 패키지 설치 및 서비스 기동, 포트 등록 - import_tasks
    # 3) 웹 서버 설정 (/var/www/html/index.html) - import_tasks
    # Play02:
    # 4) 웹 요청 - import_playbook
    ##########################################
    - name: 1) 웹서버 패키지 설치 및 서비스 가동
      ansible.builtin.include_tasks:
        file: tasks/web.yml
      vars:
        packages:
          - httpd
          - mod_ssl
        service: httpd

    - name: 2) 방화벽 패키지 설치 및 서비스 시작 및 포트 등록
      ansible.builtin.include_tasks:
        file: tasks/fw.yml
      vars:
        fw_package: firewalld
        service: firewalld
        rules:
          - http
          - https

    - name: 3) 웹 서버 설정 (/var/www/html/index.html)
      ansible.builtin.import_tasks:
        file: tasks/placeholer.yml
      vars:
        file: /var/www/html/index.html

# Play2 Web Request
- name: 웹 요청
  ansible.builtin.import_playbook: plays/test.yml
  vars:
    url: "http://ansible1.example.com"
