---
# Firewall port remove and service
- name: 방화벽 포트 제거 - {{ rules }}
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
  loop: "{{ rules }}"

- name: 방화벽 서비스 중지
  ansible.builtin.systemd:
    name: "{{ service }}"
    enabled: false
    state: stopped
