---
- name: Play01) 전체 서버 설치
  hosts: all
  tasks:
    - name: 1) 변수 포함 패키지 지정
      ansible.builtin.include_vars:
        file: package.yml

    - name: 2) 패키지 설치 - {{ package.epel_pkg }}
      ansible.builtin.include_tasks:
        file: install_package.yml
      vars:
        packages:
          epel_pkg: epel-release

    - name: 3) 패키지 설치 - {{ package.box_pkg }}
      ansible.builtin.include_tasks:
        file: install_package.yml

      vars:
        packages:
          box_pkg: boxes
