---
# playbook
- name: 웹 요청 테스트
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: 웹 요청 테스트
      ansible.builtin.uri:
        url: "{{ url  }}"
        status_code:
          - 200
        validate_certs: false
