---
- name: 0) 웹 서버 설정
  hosts: webservers
  tasks:
    ###########################################
    # 1) 패키지 설치 - httpd, firewalld
    # 2) 웹서버 설정 - /var/www/html/index.html
    # 3) 웹서버 서비스 - httpd.service, firewalld.service
    # 4) 방화벽 등록
    # 5) SELinux(?)
    ###########################################
    - name: 1) 패키지 설치 - (yum) httpd 설치
      ansible.builtin.yum:
        name:
          - httpd
          - firewalld
        state: present

    - name: 2) 웹 페이지 저장 - (copy) index.html
      ansible.builtin.copy:
        src: files/index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: 3) 웹 서비스 시작 (service) httpd
      ansible.builtin.service:
        # systemctl enable --now httpd.service
        name: httpd
        state: started
        enabled: true

    - name: 3) 방화벽 서비스 시작 - (service) firewalld.service
      # systemctl service httpd, firewall
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: true

    - name: 4) 방화벽 등록 - (firewalld) http 등록
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
