---
- name: 0) 사용자 추가
  hosts: all
  vars_files:
    vars/secret1.yml
  tasks:
    - name: 1) developer 사용자 추가
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ 'developer' | password_hash('sha512') }}"

    - name: 2) ssh-key copy
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: " {{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: 3) no passwd developer
      ansible.builtin.copy:
        src: files/developer
        dest: /etc/sudoers.d/developer
        mode: '0644'

    - name: 4) 환경 설정 - ~/.bashrc 설정
      ansible.builtin.template:
        src: templates/bashrc.j2
        dest: /home/developer/.bashrc
        owner: developer
        group: developer
        mode: '0644'

    - name: 5) 환경 설정 2 - ble.sh
      ansible.builtin.copy:
        src: files/blesh/ble.sh
        dest: /home/developer/.local/share/
        owner: developer
        group: developer
        mode: '0644'
