---
- name: 0) restore-web-db.yml
  hosts: all
  vars_files:
    - webs/webs.yml
  tasks:
    ###########################################
    # (1) 방화벽 포트 삭제 - mysql,http
    # (2) 서비스 종료 - httpd, mariadb
    # (3) 서비스 설정 - /var/www/html/index.php
    # (4) 패키지 삭제 - http
    ###########################################
    - name: 1) 방화벽 포트 제거- (firewalld) http, mysql
      become: true
      ansible.posix.firewalld:
        service: "{{ open_service }}"
        permanent: true
        immediate: true
        state: disabled


    - name: 2) 서비스 종료
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: false
        state: stopped
      loop:
        - httpd
        - mariadb

    - name: 3) 파일 삭제
      ansible.builtin.file:
        path: /var/www/html/index.php
        state: absent

    - name: 4) 패키지 삭제
      ansible.builtin.dnf:
        name:
          - httpd
          - mod_ssl
          - php
          - php-mysqld
          - php-pdo
          - mariadb
          - mariadb-server
          - python3-PyMySQL
          - mariadb-connector-c-config
          - mariadb-common
          - mariadb-connector-c
          - mariadb-errmsg
        state: absent
