---
- name: Task Failure Exercise
  hosts: databases
  gather_facts: false
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Check local Time
      ansible.builtin.command: date
      register: command_result
      changed_when: false

    - name: Print local Time
      ansible.builtin.debug:
        var: command_result
    - name: Block ~ Rescue ~ Always
      block:
        - name: Install {{ web_package }} package
          ansible.builtin.yum:
            name: "{{ web_package }}"
            state: present
            # ignore_errors: true
      rescue:
        - name: Install {{ db_package }} package
          ansible.builtin.yum:
            name: "{{ db_package }}"
            state: present
      always:
        - name: Start {{ db_service }} service
          ansible.builtin.service:
            name: "{{ db_service }}"
            state: started
            enabled: true
