---
- name: 0) restore_playbook.yml
  hosts: all
  gather_facts: false
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    # 1.mariadb 서비스 disable
    # 2.httpd 패키지 삭제
    # 3.mariadb-server 패키지 삭제
    - name: 1) DB 초기화
      block:
        - name: 1) 서비스 중지
          ansible.builtin.service:
            name: "{{ db_service  }}"
            state: stopped
            enabled: false
      always:
        - name: Remove {{ web_package }} package
          ansible.builtin.yum:
            name: "{{ web_package }}"
            state: absent

        - name: Remove {{ db_package }} package
          ansible.builtin.yum:
            name: "{{ db_package }}"
            state: absent
