---
- name: 0) DB 서버 복구
  # 1) 서비스 중지 - mariadb
  # 2) 패키지 삭제 - mariadb-server, python3-PyMySQL
  hosts: databases
  vars_files:
    - vars/main.yml
  gather_facts: false

  tasks:
    - name: 1) 파일 삭제
      ansible.builtin.file:
        path: "{{ config_file_dst }}"
        state: absent
    - name: 2) 서비스 중지 - mariadb
      ansible.builtin.service:
        name: "{{ db_services }}"
        state: stopped
        enabled: false

    - name: 3) 패키지 제거
      ansible.builtin.dnf:
        name:
          - "{{ db_packages }}"
        state: absent
