---
###############################################
# 1) 서비스 패키지 설치 - mariadb-server, httpd
# 2) 패키지 서비스 시작 - mariadb, httpd
###############################################
- name: 패키지 설치
  ansible.builtin.yum:
    name:
      - "{{ ansible_local.custom.packages.db_package }}"
      - "{{ ansible_local.custom.packages.web_package }}"
    state: present

- name: 서비스 시작 - mariadb, httpd
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - "{{ ansible_local.custom.services.db_service }}"
    - "{{ ansible_local.custom.services.web_service }}"
