---
- name: 0) 사용자 추가
  hosts: all
  become: true
  remote_user: ansible
  gather_facts: false
  vars:
    username: devops2
    pwhash: soldesk1.
  tasks:
    # 사용자 추가
    - name: 1) 사용자 추가
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ pwhash | password_hash('sha512', 'soldesklove') }}"

    # 파일 배포
    - name: 2) 파일 배포 - /etc/sudoers.d/devops2
      ansible.builtin.copy:
        src: files/devops2
        dest: /etc/sudoers.d/devops2
        mode: '0644'

    - name: 3) SSH Pub Key 생성
      ansible.posix.authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub' ) }}"
