#################################################
# 1) 서비스 중자 - mariadb
# 2) 패키지 제거 - mariadb-server ,python3-PyMySQL
#################################################
---
- name: 0) DB 웹서버 복구
  hosts: database_prob
  gather_facts: false
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
    db_svc: mariadb
  tasks:
    - name: 1) 서비스 중지
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: stopped
        enabled: false

    - name: 2) 패키지 제거
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ mariadb_packages }}"
      when: ansible_distribution == 'CentOS'
